import type { AchievementCategory } from "@/lib/achievements/types";
import type { AchievementRarity } from "@/lib/dashboard/tokens";

export type AchievementDefinitionSeed = {
  key: string;
  title: string;
  description: string;
  category: AchievementCategory;
  rarity: AchievementRarity;
  icon: string;
  xpReward: number;
  targetValue: number;
  tier?: number;
  nextTierKey?: string;
  relatedStatKey?: string;
};

/** Canonical achievement catalog — synced to `AchievementDefinition` table. */
export const ACHIEVEMENT_DEFINITION_SEEDS: AchievementDefinitionSeed[] = [
  {
    key: "clip-starter-i",
    title: "Clip Starter I",
    description: "Complete 5 clips",
    category: "learning",
    rarity: "common",
    icon: "play",
    xpReward: 0,
    targetValue: 5,
    tier: 1,
    nextTierKey: "clip-starter-ii",
    relatedStatKey: "clipsCompleted",
  },
  {
    key: "clip-starter-ii",
    title: "Clip Starter II",
    description: "Complete 25 clips",
    category: "learning",
    rarity: "common",
    icon: "play",
    xpReward: 0,
    targetValue: 25,
    tier: 2,
    nextTierKey: "scene-master-i",
    relatedStatKey: "clipsCompleted",
  },
  {
    key: "scene-master-i",
    title: "Scene Master I",
    description: "Complete 100 clips",
    category: "learning",
    rarity: "rare",
    icon: "film",
    xpReward: 0,
    targetValue: 100,
    tier: 3,
    relatedStatKey: "clipsCompleted",
  },
  {
    key: "binge-learner",
    title: "Binge Learner",
    description: "Finish 10 episodes",
    category: "learning",
    rarity: "epic",
    icon: "tv",
    xpReward: 0,
    targetValue: 10,
    relatedStatKey: "episodesFinished",
  },
  {
    key: "series-explorer",
    title: "Series Explorer",
    description: "Watch 3 different series",
    category: "learning",
    rarity: "rare",
    icon: "clapperboard",
    xpReward: 0,
    targetValue: 3,
    relatedStatKey: "seriesWatched",
  },
  {
    key: "movie-explorer",
    title: "Movie Explorer",
    description: "Finish your first movie",
    category: "learning",
    rarity: "common",
    icon: "film",
    xpReward: 0,
    targetValue: 1,
    relatedStatKey: "moviesFinished",
  },
  {
    key: "first-voice-line",
    title: "First Voice Line",
    description: "Complete your first speaking exercise",
    category: "speaking",
    rarity: "common",
    icon: "mic",
    xpReward: 0,
    targetValue: 1,
    relatedStatKey: "speakingExercises",
  },
  {
    key: "smooth-speaker-i",
    title: "Smooth Speaker I",
    description: "Reach 80% speaking accuracy 10 times",
    category: "speaking",
    rarity: "rare",
    icon: "volume2",
    xpReward: 0,
    targetValue: 10,
    nextTierKey: "smooth-speaker-ii",
    relatedStatKey: "accuracy80Sessions",
  },
  {
    key: "smooth-speaker-ii",
    title: "Smooth Speaker II",
    description: "Reach 90% accuracy 50 times",
    category: "speaking",
    rarity: "epic",
    icon: "volume2",
    xpReward: 0,
    targetValue: 50,
    relatedStatKey: "accuracy90Sessions",
  },
  {
    key: "accent-hunter",
    title: "Accent Hunter",
    description: "Practice speaking for 7 days",
    category: "speaking",
    rarity: "rare",
    icon: "mic",
    xpReward: 0,
    targetValue: 7,
    relatedStatKey: "speakingDays",
  },
  {
    key: "fast-mouth",
    title: "Fast Mouth",
    description: "Finish a speaking exercise under target time",
    category: "speaking",
    rarity: "common",
    icon: "timer",
    xpReward: 0,
    targetValue: 1,
    relatedStatKey: "fastSpeakingRuns",
  },
  {
    key: "word-collector-i",
    title: "Word Collector I",
    description: "Save 10 vocabulary words",
    category: "vocabulary",
    rarity: "common",
    icon: "bookOpen",
    xpReward: 0,
    targetValue: 10,
    tier: 1,
    nextTierKey: "word-collector-ii",
    relatedStatKey: "wordsSaved",
  },
  {
    key: "word-collector-ii",
    title: "Word Collector II",
    description: "Save 100 vocabulary words",
    category: "vocabulary",
    rarity: "rare",
    icon: "bookOpen",
    xpReward: 0,
    targetValue: 100,
    tier: 2,
    relatedStatKey: "wordsSaved",
  },
  {
    key: "memory-builder",
    title: "Memory Builder",
    description: "Review vocabulary for 7 days",
    category: "vocabulary",
    rarity: "rare",
    icon: "bookMarked",
    xpReward: 0,
    targetValue: 7,
    relatedStatKey: "vocabReviewDays",
  },
  {
    key: "vocabulary-master",
    title: "Vocabulary Master",
    description: "Master 500 saved words",
    category: "vocabulary",
    rarity: "epic",
    icon: "crown",
    xpReward: 0,
    targetValue: 500,
    relatedStatKey: "wordsMastered",
  },
  {
    key: "phrase-hunter",
    title: "Phrase Hunter",
    description: "Save 50 useful phrases",
    category: "vocabulary",
    rarity: "rare",
    icon: "bookMarked",
    xpReward: 0,
    targetValue: 50,
    relatedStatKey: "phrasesSaved",
  },
  {
    key: "day-one",
    title: "Day One",
    description: "Start your first streak",
    category: "consistency",
    rarity: "common",
    icon: "flame",
    xpReward: 0,
    targetValue: 1,
    relatedStatKey: "streakStarted",
  },
  {
    key: "focused-mind",
    title: "Focused Mind",
    description: "Maintain a 7 day streak",
    category: "consistency",
    rarity: "rare",
    icon: "flame",
    xpReward: 0,
    targetValue: 7,
    nextTierKey: "unbreakable",
    relatedStatKey: "currentStreak",
  },
  {
    key: "unbreakable",
    title: "Unbreakable",
    description: "Maintain a 30 day streak",
    category: "consistency",
    rarity: "legendary",
    icon: "flame",
    xpReward: 0,
    targetValue: 30,
    relatedStatKey: "currentStreak",
  },
  {
    key: "night-learner",
    title: "Night Learner",
    description: "Learn after 9 PM for 10 days",
    category: "consistency",
    rarity: "rare",
    icon: "moon",
    xpReward: 0,
    targetValue: 10,
    relatedStatKey: "nightLearningDays",
  },
  {
    key: "early-bird",
    title: "Early Bird",
    description: "Learn before 8 AM for 10 days",
    category: "consistency",
    rarity: "rare",
    icon: "sun",
    xpReward: 0,
    targetValue: 10,
    relatedStatKey: "morningLearningDays",
  },
  {
    key: "quick-listener",
    title: "Quick Listener",
    description: "Complete 10 clips fast",
    category: "speed",
    rarity: "common",
    icon: "zap",
    xpReward: 0,
    targetValue: 10,
    relatedStatKey: "fastClips",
  },
  {
    key: "lightning-brain",
    title: "Lightning Brain",
    description: "Complete 100 clips under target time",
    category: "speed",
    rarity: "epic",
    icon: "zap",
    xpReward: 0,
    targetValue: 100,
    relatedStatKey: "timedClips",
  },
  {
    key: "perfect-run",
    title: "Perfect Run",
    description: "Finish 10 clips without mistakes",
    category: "speed",
    rarity: "epic",
    icon: "target",
    xpReward: 0,
    targetValue: 10,
    relatedStatKey: "flawlessClips",
  },
  {
    key: "genre-hopper",
    title: "Genre Hopper",
    description: "Watch 5 genres",
    category: "exploration",
    rarity: "rare",
    icon: "sparkles",
    xpReward: 0,
    targetValue: 5,
    relatedStatKey: "genresWatched",
  },
  {
    key: "drama-expert",
    title: "Drama Expert",
    description: "Finish 100 drama clips",
    category: "exploration",
    rarity: "rare",
    icon: "theater",
    xpReward: 0,
    targetValue: 100,
    relatedStatKey: "dramaClips",
  },
  {
    key: "comedy-addict",
    title: "Comedy Addict",
    description: "Finish 100 comedy clips",
    category: "exploration",
    rarity: "rare",
    icon: "laugh",
    xpReward: 0,
    targetValue: 100,
    relatedStatKey: "comedyClips",
  },
  {
    key: "lenra-veteran",
    title: "Lenra Veteran",
    description: "Reach Level 25",
    category: "legendary",
    rarity: "legendary",
    icon: "crown",
    xpReward: 0,
    targetValue: 25,
    relatedStatKey: "level",
  },
  {
    key: "cinema-mind",
    title: "Cinema Mind",
    description: "Learn for 100 total hours",
    category: "legendary",
    rarity: "legendary",
    icon: "clock",
    xpReward: 0,
    targetValue: 100,
    relatedStatKey: "learningHours",
  },
  {
    key: "fluent-journey",
    title: "Fluent Journey",
    description: "Complete 1000 clips",
    category: "legendary",
    rarity: "legendary",
    icon: "film",
    xpReward: 0,
    targetValue: 1000,
    relatedStatKey: "clipsCompleted",
  },
];
